export const CURRENT_DATA_VERSION = '2026.09.25';

export const DEFAULT_CHANNELS = [
  { key: 'dine_in', name: '內用/紙本', markupPercent: 0, roundMode: 'round1' },
  { key: 'pos', name: '微碧/POS', markupPercent: 0, roundMode: 'round1' },
  { key: 'uber', name: 'Uber Eats', markupPercent: 30, roundMode: 'end9' },
  { key: 'panda', name: 'Foodpanda', markupPercent: 30, roundMode: 'end9' },
];

export const DEFAULT_CATEGORIES = ['熱炒', '炸物', '烤物', '蝦料理', '湯品', '飯&麵'];

export const DEFAULT_INGREDIENTS = [
  { name: '味噌', aliases: [] },
  { name: '蝦', aliases: ['蝦仁', '鮮蝦', '蝦球', '泰國蝦', '櫻花蝦'] },
  { name: '牛', aliases: ['牛肉', '牛小排'] },
  { name: '豬', aliases: ['豬肉', '肉絲', '松阪豬', '鹹豬肉', '排骨', '大腸', '肥腸'] },
  { name: '雞', aliases: ['雞肉', '雞丁', '雞腿排', '雞翅'] },
  { name: '蛋', aliases: ['皮蛋', '滑蛋', '鹹蛋'] },
  { name: '魚', aliases: ['鮮魚', '鱸魚', '台灣鯛', '香魚', '鯖魚', '魚下巴', '魟魚', '魚片'] },
  { name: '鴨', aliases: ['鴨血'] },
  { name: '貝', aliases: ['蚵仔', '鮮蚵', '蛤蠣', '干貝', '螺肉'] },
  { name: '中卷', aliases: [] },
  { name: '薑', aliases: ['薑絲', '薑片'] },
  { name: '菇', aliases: ['杏鮑菇', '猴頭菇', '雨來菇'] },
  { name: '菜', aliases: ['高麗菜', '芹菜', '酸菜', '九層塔'] },
  { name: '瓜', aliases: ['苦瓜', '絲瓜'] },
  { name: '漿', aliases: ['花枝丸', '黑輪片'] },
  { name: '豆腐', aliases: [] },
  { name: '梅子', aliases: [] },
  { name: '剝皮辣椒', aliases: [] },
  { name: '飯', aliases: ['炒飯', '燴飯'] },
  { name: '麵', aliases: ['炒麵', '炒泡麵', '炒烏龍'] },
  { name: '湯', aliases: [] },
];

export const DEFAULT_METHODS = [
  '塔香',
  '宮保',
  '金沙',
  '黑胡椒',
  '川味',
  '糖醋',
  '蜜汁',
  '三杯',
  '鹽烤',
  '烤',
  '椒鹽',
  '鹽酥',
  '香酥',
  '清炒',
  '回鍋',
  '奶油',
  '麻油',
  '清酒',
  '蔥爆',
  '避風塘',
];

export const DEFAULT_DISHES = [
  {
    id: 1,
    name: '皮蛋牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['皮蛋', '牛肉'],
    active: true,
    prices: {
      dine_in: 220,
      pos: 220,
      uber: 275,
      panda: 289,
    },
  },
  {
    id: 2,
    name: '蔥爆豬肉',
    mode: 'combine',
    category: '熱炒',
    method: '蔥爆',
    ingredients: ['豬肉'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 3,
    name: '蔥爆牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '蔥爆',
    ingredients: ['牛肉'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 4,
    name: '蔥爆松阪豬',
    mode: 'combine',
    category: '熱炒',
    method: '蔥爆',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 5,
    name: '蔥爆中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '蔥爆',
    ingredients: ['中卷'],
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 6,
    name: '蔥爆雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '蔥爆',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 7,
    name: '塔香蛤蠣',
    mode: 'combine',
    category: '熱炒',
    method: '塔香',
    ingredients: ['蛤蠣'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 8,
    name: '塔香雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '塔香',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 9,
    name: '塔香螺肉',
    mode: 'combine',
    category: '熱炒',
    method: '塔香',
    ingredients: ['螺肉'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 10,
    name: '塔香中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '塔香',
    ingredients: ['中卷'],
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 11,
    name: '宮保皮蛋',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['皮蛋'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 12,
    name: '宮保杏鮑菇',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['杏鮑菇'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 13,
    name: '宮保雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 14,
    name: '宮保蝦球',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['蝦球'],
    prices: {
      dine_in: 280,
      pos: 280,
      uber: 350,
      panda: 369,
    },
  },
  {
    id: 15,
    name: '宮保豆腐',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['豆腐'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 16,
    name: '宮保魚片',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['魚片'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 17,
    name: '宮保干貝',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['干貝'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 18,
    name: '宮保中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['中卷'],
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 19,
    name: '宮保排骨',
    mode: 'combine',
    category: '熱炒',
    method: '宮保',
    ingredients: ['排骨'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 20,
    name: '金沙魚片',
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['魚片'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 21,
    name: '金沙杏鮑菇',
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['杏鮑菇'],
    active: true,
    prices: {
      dine_in: 170,
      pos: 170,
      uber: 215,
      panda: 229,
    },
  },
  {
    id: 22,
    name: '金沙豆腐',
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['豆腐'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 23,
    name: '金沙鮮蚵',
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['鮮蚵'],
    active: true,
    prices: {
      dine_in: 200,
      pos: 200,
      uber: 250,
      panda: 259,
    },
  },
  {
    id: 24,
    name: '金沙中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['中卷'],
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 25,
    name: '金沙蝦球',
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['蝦球'],
    active: true,
    prices: {
      dine_in: 295,
      pos: 295,
      uber: 370,
      panda: 389,
    },
  },
  {
    id: 26,
    name: '金沙雞丁',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '金沙',
    ingredients: ['雞丁'],
    prices: {
      dine_in: 200,
      pos: 200,
      uber: 250,
      panda: 269,
    },
  },
  {
    id: 27,
    name: '黑胡椒松阪豬',
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 28,
    name: '黑胡椒牛小排',
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['牛小排'],
    active: true,
    prices: {
      dine_in: 285,
      pos: 285,
      uber: 360,
      panda: 379,
    },
  },
  {
    id: 29,
    name: '黑胡椒蝦球',
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['蝦球'],
    active: true,
    prices: {
      dine_in: 285,
      pos: 285,
      uber: 360,
      panda: 379,
    },
  },
  {
    id: 30,
    name: '黑胡椒雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 200,
      pos: 200,
      uber: 250,
      panda: 259,
    },
  },
  {
    id: 31,
    name: '黑胡椒中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['中卷'],
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 32,
    name: '黑胡椒排骨',
    mode: 'combine',
    category: '熱炒',
    method: '黑胡椒',
    ingredients: ['排骨'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 33,
    name: '回鍋肉',
    mode: 'combine',
    category: '熱炒',
    method: '回鍋',
    ingredients: ['豬肉'],
    active: true,
    prices: {
      dine_in: 200,
      pos: 200,
      uber: 250,
      panda: 259,
    },
  },
  {
    id: 34,
    name: '回鍋肥腸',
    mode: 'combine',
    category: '熱炒',
    method: '回鍋',
    ingredients: ['肥腸'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 35,
    name: '唐揚雞',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['雞肉'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 36,
    name: '薑絲大腸',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['薑絲', '大腸'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 37,
    name: '客家鹹豬肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['鹹豬肉'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 38,
    name: '客家小炒',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['肉絲'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 39,
    name: '丁香花生',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: [],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 40,
    name: '麻油松阪豬',
    mode: 'combine',
    category: '熱炒',
    method: '麻油',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 41,
    name: '奶油蛤蠣',
    mode: 'combine',
    category: '熱炒',
    method: '奶油',
    ingredients: ['蛤蠣'],
    active: true,
    prices: {
      dine_in: 220,
      pos: 220,
      uber: 275,
      panda: 289,
    },
  },
  {
    id: 42,
    name: '清酒蛤蠣',
    mode: 'combine',
    category: '熱炒',
    method: '清酒',
    ingredients: ['蛤蠣'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 43,
    name: '絲瓜蛤蠣',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['絲瓜', '蛤蠣'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 44,
    name: '五更腸旺',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['大腸', '鴨血'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 45,
    name: '麻辣鴨血',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['鴨血'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 46,
    name: '滑蛋絲瓜',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['滑蛋', '絲瓜'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 47,
    name: '滑蛋蝦仁',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['滑蛋', '蝦仁'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 48,
    name: '滑蛋牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['滑蛋', '牛肉'],
    active: true,
    prices: {
      dine_in: 220,
      pos: 220,
      uber: 275,
      panda: 289,
    },
  },
  {
    id: 49,
    name: '滑蛋肉絲',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['滑蛋', '肉絲'],
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 50,
    name: '川味牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['牛肉'],
    active: true,
    prices: {
      dine_in: 350,
      pos: 350,
      uber: 440,
      panda: 459,
    },
  },
  {
    id: 51,
    name: '川味中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['中卷'],
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 52,
    name: '川味松阪豬',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 53,
    name: '川味黑輪片',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['黑輪片'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 54,
    name: '川味雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 55,
    name: '川味干貝',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['干貝'],
    active: true,
    prices: {
      dine_in: 270,
      pos: 270,
      uber: 340,
      panda: 359,
    },
  },
  {
    id: 56,
    name: '川味豆腐',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['豆腐'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 57,
    name: '川味蝦球',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['蝦球'],
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 58,
    name: '川味魚片',
    mode: 'combine',
    category: '熱炒',
    method: '川味',
    ingredients: ['魚片'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 59,
    name: '三杯杏鮑菇',
    mode: 'combine',
    category: '熱炒',
    method: '三杯',
    ingredients: ['杏鮑菇'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 60,
    name: '三杯中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '三杯',
    ingredients: ['中卷'],
    prices: {
      dine_in: 310,
      pos: 310,
      uber: 390,
      panda: 409,
    },
  },
  {
    id: 61,
    name: '三杯雞',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '三杯',
    ingredients: ['雞'],
    prices: {
      dine_in: 310,
      pos: 310,
      uber: 390,
      panda: 409,
    },
  },
  {
    id: 62,
    name: '三杯皮蛋',
    mode: 'combine',
    category: '熱炒',
    method: '三杯',
    ingredients: ['皮蛋'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 63,
    name: '三杯魟魚',
    mode: 'combine',
    category: '熱炒',
    method: '三杯',
    ingredients: ['魟魚'],
    active: true,
    prices: {
      dine_in: 380,
      pos: 380,
      uber: 475,
      panda: 499,
    },
  },
  {
    id: 64,
    name: '糖醋松阪豬',
    mode: 'combine',
    category: '熱炒',
    method: '糖醋',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 65,
    name: '糖醋排骨',
    mode: 'combine',
    category: '熱炒',
    method: '糖醋',
    ingredients: ['排骨'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 66,
    name: '糖醋蝦球',
    mode: 'combine',
    category: '熱炒',
    method: '糖醋',
    ingredients: ['蝦球'],
    active: true,
    prices: {
      dine_in: 295,
      pos: 295,
      uber: 370,
      panda: 389,
    },
  },
  {
    id: 67,
    name: '糖醋豆腐',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '糖醋',
    ingredients: ['豆腐'],
    prices: {
      dine_in: 195,
      pos: 195,
      uber: 245,
      panda: 259,
    },
  },
  {
    id: 68,
    name: '糖醋魚片',
    mode: 'combine',
    category: '熱炒',
    method: '糖醋',
    ingredients: ['魚片'],
    active: true,
    prices: {
      dine_in: 250,
      pos: 250,
      uber: 315,
      panda: 329,
    },
  },
  {
    id: 69,
    name: '蜜汁雞丁',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['雞丁'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 70,
    name: '蜜汁排骨',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['排骨'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 71,
    name: '蜜汁中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['中卷'],
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 72,
    name: '蜜汁蝦球',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['蝦球'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 73,
    name: '蜜汁黑輪片',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['黑輪片'],
    active: true,
    prices: {
      dine_in: 150,
      pos: 150,
      uber: 190,
      panda: 199,
    },
  },
  {
    id: 74,
    name: '蜜汁雞翅',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['雞翅'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 75,
    name: '蜜汁干貝',
    mode: 'combine',
    category: '熱炒',
    method: '蜜汁',
    ingredients: ['干貝'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 76,
    name: '紅燒豆腐',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['豆腐'],
    active: true,
    prices: {
      dine_in: 170,
      pos: 170,
      uber: 215,
      panda: 229,
    },
  },
  {
    id: 77,
    name: '酸菜魚片',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['酸菜', '魚片'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 78,
    name: '酸菜牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['酸菜', '牛肉'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 79,
    name: '酸菜豬肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['酸菜', '豬肉'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 80,
    name: '蔥蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: [],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 81,
    name: '菜脯蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: [],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 82,
    name: '九層塔蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['九層塔'],
    active: true,
    prices: {
      dine_in: 130,
      pos: 130,
      uber: 165,
      panda: 169,
    },
  },
  {
    id: 83,
    name: '雨來菇炒蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['雨來菇'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 84,
    name: '蚵仔蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['蚵仔'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 85,
    name: '剝皮辣椒蛋',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['剝皮辣椒'],
    active: true,
    prices: {
      dine_in: 150,
      pos: 150,
      uber: 190,
      panda: 199,
    },
  },
  {
    id: 86,
    name: '芹菜蝦球',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['芹菜', '蝦球'],
    active: true,
    prices: {
      dine_in: 295,
      pos: 295,
      uber: 370,
      panda: 389,
    },
  },
  {
    id: 87,
    name: '芹菜中卷',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['芹菜', '中卷'],
    prices: {
      dine_in: 230,
      pos: 230,
      uber: 290,
      panda: 299,
    },
  },
  {
    id: 88,
    name: '芹菜牛肉',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['芹菜', '牛肉'],
    active: true,
    prices: {
      dine_in: 230,
      pos: 230,
      uber: 290,
      panda: 299,
    },
  },
  {
    id: 89,
    name: '時令季節鮮蔬',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: [],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 90,
    name: '苦瓜鹹蛋',
    active: true,
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['苦瓜', '鹹蛋'],
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 91,
    name: '梅子雞',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['梅子', '雞肉'],
    active: true,
    prices: {
      dine_in: 330,
      pos: 330,
      uber: 415,
      panda: 429,
    },
  },
  {
    id: 92,
    name: '薑片雞翅',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['薑片', '雞翅'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 93,
    name: '薑片雞',
    mode: 'combine',
    category: '熱炒',
    method: '',
    ingredients: ['薑片', '雞肉'],
    active: true,
    prices: {
      dine_in: 280,
      pos: 280,
      uber: 350,
      panda: 369,
    },
  },
  {
    id: 94,
    name: '一夜干',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['鮮魚'],
    active: true,
    prices: {
      dine_in: 310,
      pos: 310,
      uber: 390,
      panda: 409,
    },
  },
  {
    id: 95,
    name: '鹽烤台灣鯛',
    mode: 'combine',
    category: '烤物',
    method: '鹽烤',
    ingredients: ['台灣鯛'],
    active: true,
    prices: {
      dine_in: 300,
      pos: 300,
      uber: 375,
      panda: 390,
    },
  },
  {
    id: 96,
    name: '鹽烤胡椒魚',
    mode: 'combine',
    category: '烤物',
    method: '鹽烤',
    ingredients: ['鮮魚'],
    active: true,
    prices: {
      dine_in: 330,
      pos: 330,
      uber: 415,
      panda: 429,
    },
  },
  {
    id: 97,
    name: '鹽烤鱸魚',
    mode: 'combine',
    category: '烤物',
    method: '鹽烤',
    ingredients: ['鱸魚'],
    active: true,
    prices: {
      dine_in: 390,
      pos: 390,
      uber: 490,
      panda: 509,
    },
  },
  {
    id: 98,
    name: '鹽烤胡椒鱸魚',
    mode: 'combine',
    category: '烤物',
    method: '鹽烤',
    ingredients: ['鱸魚'],
    active: true,
    prices: {
      dine_in: 450,
      pos: 450,
      uber: 565,
      panda: 589,
    },
  },
  {
    id: 99,
    name: '鹽烤泰國蝦',
    mode: 'combine',
    category: '烤物',
    method: '鹽烤',
    ingredients: ['泰國蝦'],
    active: true,
    prices: {
      dine_in: 510,
      pos: 510,
      uber: 640,
      panda: 669,
    },
  },
  {
    id: 100,
    name: '烤香魚(1支)',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['香魚'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 101,
    name: '烤鯖魚(2支)',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['鯖魚'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 102,
    name: '烤魚下巴',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['魚下巴'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 103,
    name: '烤雞翅',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['雞翅'],
    active: true,
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 104,
    name: '烤雞腿排',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['雞腿排'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 105,
    name: '烤牛小排',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['牛小排'],
    active: true,
    prices: {
      dine_in: 280,
      pos: 280,
      uber: 350,
      panda: 369,
    },
  },
  {
    id: 106,
    name: '烤松阪豬',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['松阪豬'],
    active: true,
    prices: {
      dine_in: 260,
      pos: 260,
      uber: 325,
      panda: 339,
    },
  },
  {
    id: 107,
    name: '烤鹹豬肉',
    mode: 'combine',
    category: '烤物',
    method: '烤',
    ingredients: ['鹹豬肉'],
    active: true,
    prices: {
      dine_in: 210,
      pos: 210,
      uber: 265,
      panda: 279,
    },
  },
  {
    id: 108,
    name: '白灼鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 109,
    name: '蔥爆鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '蔥爆',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 110,
    name: '金沙鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '金沙',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 111,
    name: '蜜汁鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '蜜汁',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 112,
    name: '宮保鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '宮保',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 113,
    name: '塔香鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '塔香',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 114,
    name: '川味鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '川味',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 115,
    name: '黑胡椒鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '黑胡椒',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 298,
      pos: 298,
      uber: 375,
      panda: 389,
    },
  },
  {
    id: 116,
    name: '三杯鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '三杯',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 350,
      pos: 350,
      uber: 440,
      panda: 459,
    },
  },
  {
    id: 117,
    name: '避風塘鮮蝦',
    mode: 'combine',
    category: '蝦料理',
    method: '避風塘',
    ingredients: ['鮮蝦'],
    active: true,
    prices: {
      dine_in: 350,
      pos: 350,
      uber: 440,
      panda: 459,
    },
  },
  {
    id: 118,
    name: '香酥花枝丸',
    mode: 'combine',
    category: '炸物',
    method: '香酥',
    ingredients: ['花枝丸'],
    active: true,
    prices: {
      dine_in: 189,
      pos: 189,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 119,
    name: '香酥鮮蚵',
    mode: 'combine',
    category: '炸物',
    method: '香酥',
    ingredients: ['鮮蚵'],
    active: true,
    prices: {
      dine_in: 195,
      pos: 195,
      uber: 245,
      panda: 259,
    },
  },
  {
    id: 120,
    name: '香酥肥腸',
    mode: 'combine',
    category: '炸物',
    method: '香酥',
    ingredients: ['肥腸'],
    active: true,
    prices: {
      dine_in: 195,
      pos: 195,
      uber: 245,
      panda: 259,
    },
  },
  {
    id: 121,
    name: '鹽酥肥腸',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['肥腸'],
    prices: {
      dine_in: 200,
      pos: 200,
      uber: 250,
      panda: 259,
    },
  },
  {
    id: 122,
    name: '鹽酥皮蛋',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['皮蛋'],
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 123,
    name: '鹽酥杏鮑菇',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['杏鮑菇'],
    prices: {
      dine_in: 180,
      pos: 180,
      uber: 225,
      panda: 239,
    },
  },
  {
    id: 124,
    name: '鹽酥雞肉',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['雞肉'],
    prices: {
      dine_in: 185,
      pos: 185,
      uber: 235,
      panda: 249,
    },
  },
  {
    id: 125,
    name: '鹽酥黑輪片',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['黑輪片'],
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 126,
    name: '鹽酥蝦球',
    active: true,
    mode: 'combine',
    category: '炸物',
    method: '鹽酥',
    ingredients: ['蝦球'],
    prices: {
      dine_in: 295,
      pos: 295,
      uber: 370,
      panda: 389,
    },
  },
  {
    id: 127,
    name: '椒鹽排骨',
    mode: 'combine',
    category: '炸物',
    method: '椒鹽',
    ingredients: ['排骨'],
    active: true,
    prices: {
      dine_in: 230,
      pos: 230,
      uber: 290,
      panda: 299,
    },
  },
  {
    id: 128,
    name: '椒鹽中卷',
    mode: 'combine',
    category: '炸物',
    method: '椒鹽',
    ingredients: [],
    active: true,
    prices: {
      dine_in: 290,
      pos: 290,
      uber: 365,
      panda: 379,
    },
  },
  {
    id: 129,
    name: '椒鹽牛小排',
    mode: 'combine',
    category: '炸物',
    method: '椒鹽',
    ingredients: ['牛小排'],
    active: true,
    prices: {
      dine_in: 280,
      pos: 280,
      uber: 350,
      panda: 369,
    },
  },
  {
    id: 130,
    name: '椒鹽干貝',
    mode: 'combine',
    category: '炸物',
    method: '椒鹽',
    ingredients: ['干貝'],
    active: true,
    prices: {
      dine_in: 290,
      pos: 290,
      uber: 365,
      panda: 379,
    },
  },
  {
    id: 131,
    name: '蚵仔湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['蚵仔', '湯'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 132,
    name: '蛤蠣湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['蛤蠣', '湯'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
  {
    id: 133,
    name: '味噌鮮魚湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['味噌', '鮮魚', '湯'],
    active: true,
    prices: {
      dine_in: 190,
      pos: 190,
      uber: 240,
      panda: 249,
    },
  },
  {
    id: 134,
    name: '豆腐蛋花湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['豆腐', '湯'],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 135,
    name: '味噌豆腐蛤蠣湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['味噌', '豆腐', '蛤蠣', '湯'],
    active: true,
    prices: {
      dine_in: 220,
      pos: 220,
      uber: 275,
      panda: 289,
    },
  },
  {
    id: 136,
    name: '鳳梨苦瓜雞湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['苦瓜', '雞肉', '湯'],
    active: true,
    prices: {
      dine_in: 550,
      pos: 550,
      uber: 690,
      panda: 719,
    },
  },
  {
    id: 137,
    name: '剝皮辣椒雞湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['剝皮辣椒', '雞肉', '湯'],
    active: true,
    prices: {
      dine_in: 550,
      pos: 550,
      uber: 690,
      panda: 719,
    },
  },
  {
    id: 138,
    name: '麻香猴頭菇鮮雞湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['猴頭菇', '雞肉', '湯'],
    active: true,
    prices: {
      dine_in: 580,
      pos: 580,
      uber: 725,
      panda: 759,
    },
  },
  {
    id: 139,
    name: '藥膳人蔘雞湯',
    active: true,
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['雞肉', '湯'],
    prices: {
      dine_in: 600,
      pos: 600,
      uber: 750,
      panda: 779,
    },
  },
  {
    id: 140,
    name: '鱸魚蛤蠣湯',
    mode: 'combine',
    category: '湯品',
    method: '',
    ingredients: ['鱸魚', '蛤蠣', '湯'],
    active: true,
    prices: {
      dine_in: 500,
      pos: 500,
      uber: 625,
      panda: 649,
    },
  },
  {
    id: 141,
    name: '豬肉燴飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['豬肉', '燴飯'],
    active: true,
    prices: {
      dine_in: 130,
      pos: 130,
      uber: 165,
      panda: 169,
    },
  },
  {
    id: 142,
    name: '牛肉燴飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['牛肉', '燴飯'],
    active: true,
    prices: {
      dine_in: 130,
      pos: 130,
      uber: 165,
      panda: 169,
    },
  },
  {
    id: 143,
    name: '雞丁燴飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['雞丁', '燴飯'],
    active: true,
    prices: {
      dine_in: 130,
      pos: 130,
      uber: 165,
      panda: 169,
    },
  },
  {
    id: 144,
    name: '鮮蔬炒麵',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['炒麵'],
    active: true,
    prices: {
      dine_in: 100,
      pos: 100,
      uber: 125,
      panda: 129,
    },
  },
  {
    id: 145,
    name: '三鮮炒麵',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['炒麵'],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 146,
    name: '炒泡麵',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['炒泡麵'],
    active: true,
    prices: {
      dine_in: 90,
      pos: 90,
      uber: 115,
      panda: 119,
    },
  },
  {
    id: 147,
    name: '炒烏龍麵',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['炒烏龍'],
    active: true,
    prices: {
      dine_in: 100,
      pos: 100,
      uber: 125,
      panda: 129,
    },
  },
  {
    id: 148,
    name: '蝦仁蛋炒飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['蝦仁', '炒飯'],
    active: true,
    prices: {
      dine_in: 120,
      pos: 120,
      uber: 150,
      panda: 159,
    },
  },
  {
    id: 149,
    name: '肉絲蛋炒飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['肉絲', '炒飯'],
    active: true,
    prices: {
      dine_in: 90,
      pos: 90,
      uber: 115,
      panda: 119,
    },
  },
  {
    id: 150,
    name: '櫻花蝦炒飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['櫻花蝦', '炒飯'],
    active: true,
    prices: {
      dine_in: 130,
      pos: 130,
      uber: 165,
      panda: 169,
    },
  },
  {
    id: 151,
    name: '古早味蚵仔炒飯',
    mode: 'combine',
    category: '飯&麵',
    method: '',
    ingredients: ['蚵仔', '炒飯'],
    active: true,
    prices: {
      dine_in: 160,
      pos: 160,
      uber: 200,
      panda: 209,
    },
  },
];

export const DEFAULT_PACKAGES = [
  {
    id: 1790271059913,
    name: '3890',
    active: true,
    prices: {
      dine_in: 3890,
      pos: 3890,
      uber: 4865,
      panda: 5059,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['鹽烤台灣鯛'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['鹽烤胡椒魚', '鹽烤鱸魚'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['椒鹽牛小排', '黑胡椒牛小排'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['絲瓜蛤蠣'],
      },
      {
        name: '菜5',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜6',
        autoSort: true,
        dishNames: ['金沙魟魚'],
      },
      {
        name: '菜7',
        autoSort: true,
        dishNames: ['川味牛肉'],
      },
      {
        name: '菜8',
        autoSort: true,
        dishNames: ['香酥花枝丸', '剝皮辣椒蛋'],
      },
      {
        name: '菜9',
        autoSort: true,
        dishNames: ['香酥鮮蚵'],
      },
      {
        name: '菜10',
        autoSort: true,
        dishNames: ['三杯泰國蝦', '避風塘鮮蝦', '鹽烤泰國蝦'],
      },
      {
        name: '菜11',
        autoSort: true,
        dishNames: ['椒鹽排骨', '黑胡椒排骨', '蜜汁排骨', '糖醋排骨'],
      },
      {
        name: '菜12',
        autoSort: true,
        dishNames: ['薑絲大腸'],
      },
      {
        name: '菜13',
        autoSort: true,
        dishNames: ['蔥爆松阪豬'],
      },
      {
        name: '菜14',
        autoSort: true,
        dishNames: ['梅子雞'],
      },
      {
        name: '菜15',
        autoSort: true,
        dishNames: ['回鍋肥腸'],
      },
      {
        name: '湯1',
        autoSort: true,
        dishNames: ['剝皮辣椒雞湯', '麻香猴頭菇鮮雞湯', '鳳梨苦瓜雞湯', '藥膳人蔘雞湯'],
      },
    ],
  },
  {
    id: 1790270771764,
    name: '3250',
    active: true,
    prices: {
      dine_in: 3250,
      pos: 3250,
      uber: 4065,
      panda: 4229,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['川味蝦球', '金沙蝦球', '宮保蝦球', '蜜汁蝦球', '鳳梨蝦球'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['川味豆腐', '紅燒豆腐', '塔香豆腐'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['三杯魟魚'],
      },
      {
        name: '菜5',
        autoSort: true,
        dishNames: ['客家小炒'],
      },
      {
        name: '菜6',
        autoSort: true,
        dishNames: ['薑煸雞'],
      },
      {
        name: '菜7',
        autoSort: true,
        dishNames: ['香酥鮮蚵'],
      },
      {
        name: '菜8',
        autoSort: true,
        dishNames: ['鹽烤台灣鯛', '鹽烤胡椒魚', '鹽烤鱸魚'],
      },
      {
        name: '菜9',
        autoSort: true,
        dishNames: ['回鍋肉'],
      },
      {
        name: '菜10',
        autoSort: true,
        dishNames: ['椒鹽牛小排', '黑胡椒牛小排'],
      },
      {
        name: '菜11',
        autoSort: true,
        dishNames: ['鹽烤泰國蝦'],
      },
      {
        name: '湯1',
        autoSort: true,
        dishNames: ['剝皮辣椒雞湯', '麻香猴頭菇鮮雞湯', '鳳梨苦瓜雞湯', '藥膳人蔘雞湯'],
      },
    ],
  },
  {
    id: 1790270114630,
    name: '1499',
    active: true,
    prices: {
      dine_in: 1489,
      pos: 1489,
      uber: 1865,
      panda: 1939,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['芹菜中卷', '芹菜牛肉'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['滑蛋牛肉', '滑蛋肉絲', '滑蛋蝦仁'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['金沙杏鮑菇', '黑胡椒杏鮑菇', '塔香杏鮑菇', '鹽酥杏鮑菇'],
      },
      {
        name: '菜5',
        autoSort: true,
        dishNames: ['蜜汁排骨', '糖醋排骨'],
      },
      {
        name: '菜6',
        autoSort: true,
        dishNames: ['薑絲大腸'],
      },
      {
        name: '菜7',
        autoSort: true,
        dishNames: ['鹽烤台灣鯛', '鹽烤胡椒魚', '鹽烤鱸魚'],
      },
      {
        name: '菜8',
        autoSort: true,
        dishNames: ['宮保豆腐'],
      },
      {
        name: '菜9',
        autoSort: true,
        dishNames: ['宮保皮蛋', '鹽酥皮蛋'],
      },
      {
        name: '湯1',
        autoSort: true,
        dishNames: ['豆腐蛋花湯', '味噌鮮魚湯', '蚵仔湯', '蛤蠣湯'],
      },
    ],
  },
  {
    id: 1790269821174,
    name: '1149',
    active: true,
    prices: {
      dine_in: 1149,
      pos: 1149,
      uber: 1440,
      panda: 1499,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['絲瓜蛤蠣'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['椒鹽雞翅', '蜜汁雞翅'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['鹽烤台灣鯛'],
      },
      {
        name: '菜5',
        autoSort: true,
        dishNames: ['客家小炒'],
      },
      {
        name: '菜6',
        autoSort: true,
        dishNames: ['麻辣鴨血'],
      },
      {
        name: '菜7',
        autoSort: true,
        dishNames: ['雨來菇炒蛋'],
      },
      {
        name: '湯1',
        autoSort: true,
        dishNames: ['豆腐蛋花湯', '味噌鮮魚湯', '蚵仔湯', '蛤蠣湯'],
      },
    ],
  },
  {
    id: 1790269650132,
    name: '949',
    active: true,
    prices: {
      dine_in: 949,
      pos: 949,
      uber: 1190,
      panda: 1239,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['菜脯蛋', '蔥蛋', '剝皮辣椒蛋'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['川味豆腐', '塔香豆腐', '糖醋豆腐'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['鹽烤台灣鯛'],
      },
      {
        name: '菜5',
        autoSort: true,
        dishNames: ['蔥爆中卷', '蔥爆牛肉', '蔥爆豬肉', '蔥爆雞丁'],
      },
      {
        name: '湯1',
        autoSort: true,
        dishNames: ['豆腐蛋花湯', '味噌鮮魚湯', '蚵仔湯', '蛤蠣湯'],
      },
    ],
  },
  {
    id: 1790264968948,
    name: '699',
    active: true,
    prices: {
      dine_in: 699,
      pos: 699,
      uber: 875,
      panda: 909,
    },
    slots: [
      {
        name: '菜1',
        autoSort: true,
        dishNames: ['時令季節鮮蔬'],
      },
      {
        name: '菜2',
        autoSort: true,
        dishNames: ['醬爆牛肉', '醬爆豬肉', '醬爆雞丁'],
      },
      {
        name: '菜3',
        autoSort: true,
        dishNames: ['鹽酥黑輪片'],
      },
      {
        name: '菜4',
        autoSort: true,
        dishNames: ['菜脯蛋', '蔥蛋'],
      },
      {
        name: '湯',
        autoSort: true,
        dishNames: ['豆腐蛋花湯', '味噌鮮魚湯', '蚵仔湯', '蛤蠣湯'],
      },
    ],
  },
];
